/**
 * Service for interacting with OpenAI-compatible LLM APIs.
 */
export class AIService {
  private apiUrl: string;
  private apiKey: string;
  private model: string;

  constructor(
    apiUrl: string = process.env.OPENAI_API_BASE || 'https://api.openai.com/v1',
    apiKey: string = process.env.OPENAI_API_KEY || '',
    model: string = process.env.OPENAI_API_MODEL || 'gpt-4o'
  ) {
    this.apiUrl = apiUrl;
    this.apiKey = apiKey;
    this.model = model;
  }

  /**
   * Prompts the AI model and returns the generated text response.
   * 
   * @param prompt The question or instruction for the AI
   * @returns The text generated by the AI
   */
  async ask(prompt: string): Promise<string> {
    if (!this.apiKey) {
      throw new Error('AIService requires an API key. Set OPENAI_API_KEY environment variable.');
    }

    const response = await fetch(`${this.apiUrl}/chat/completions`, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        'Authorization': `Bearer ${this.apiKey}`
      },
      body: JSON.stringify({
        model: this.model,
        messages: [{ role: 'user', content: prompt }]
      })
    });

    if (!response.ok) {
      const errorData = await response.text();
      throw new Error(`AI API Error (${response.status}): ${errorData}`);
    }

    const data = await response.json() as any;
    
    if (data.choices && data.choices.length > 0) {
      return data.choices[0].message.content;
    }

    throw new Error('Unexpected response format from AI API.');
  }
}
