import { GoogleGenAI } from '@google/genai';

/**
 * Service for interacting with Gemini AI Models
 */
export class AIService {
  private client: GoogleGenAI;
  private model: string;

  constructor(
    apiKey: string = process.env.GEMINI_API_KEY || '',
    model: string = process.env.GEMINI_MODEL || ''
  ) {
    this.client = new GoogleGenAI({ apiKey });
    this.model = model;
  }

  /**
   * Prompts the Gemini model and returns the generated text response.
   * 
   * @param prompt The question or instruction for the AI
   * @returns The text generated by the AI
   */
  async ask(prompt: string): Promise<string> {
    try {
      const response = await this.client.models.generateContent({
        model: this.model,
        contents: prompt,
        config: {
          systemInstruction: "You are a helpful assistant responding on WhatsApp. NEVER use standard Markdown like **, ##, or HTML. ONLY use WhatsApp text formatting: *bold*, _italic_, ~strikethrough~, and ```monospace```. Keep your layout clean and use normal dashes for bullet points.",
        }
      });

      if (response && response.text) {
        return response.text;
      }

      throw new Error('Unexpected response format from AI API.');
    } catch (error: any) {
      throw new Error(`AI API Error: ${error.message}`);
    }
  }
}
