import { GoogleGenAI } from '@google/genai';
import { prisma } from '@assistant/database';

/**
 * Service for interacting with Gemini AI Models
 */
export class AIService {
  private client: GoogleGenAI | null = null;
  private currentApiKey: string | null = null;

  constructor() {}

  private async getClientAndModel(): Promise<{ client: GoogleGenAI; model: string }> {
    const dbKey = await prisma.setting.findUnique({ where: { key: 'AI_API_KEY' } });
    const dbModel = await prisma.setting.findUnique({ where: { key: 'AI_MODEL' } });

    const apiKey = dbKey?.value || process.env.GEMINI_API_KEY || '';
    const model = dbModel?.value || process.env.GEMINI_MODEL || 'gemini-2.5-flash';

    if (!apiKey) {
      throw new Error('AI API Key is not configured in Settings or .env');
    }

    if (this.currentApiKey !== apiKey || !this.client) {
      this.client = new GoogleGenAI({ apiKey });
      this.currentApiKey = apiKey;
    }

    return { client: this.client, model };
  }

  /**
   * Prompts the Gemini model and returns the generated text response.
   * 
   * @param prompt The question or instruction for the AI
   * @returns The text generated by the AI
   */
  async ask(prompt: string, media?: { mimetype: string; data: string }[]): Promise<string> {
    try {
      const { client, model } = await this.getClientAndModel();

      let contents: any = prompt;

      if (media && media.length > 0) {
        const parts: any[] = [{ text: prompt }];
        for (const item of media) {
          parts.push({
            inlineData: {
              data: item.data,
              mimeType: item.mimetype
            }
          });
        }
        contents = parts;
      }

      const response = await client.models.generateContent({
        model: model,
        contents: contents,
        config: {
          systemInstruction: "You are a helpful assistant responding on WhatsApp. NEVER use standard Markdown like **, ##, or HTML. ONLY use WhatsApp text formatting: *bold*, _italic_, ~strikethrough~, and ```monospace```. Keep your layout clean and use normal dashes for bullet points.",
        }
      });

      if (response && response.text) {
        return response.text;
      }

      throw new Error('Unexpected response format from AI API.');
    } catch (error: any) {
      throw new Error(`AI API Error: ${error.message}`);
    }
  }

  /**
   * Generates a 768-dimensional vector embedding natively using Gemini.
   */
  async embed(text: string): Promise<number[]> {
    try {
      const { client } = await this.getClientAndModel();
      const response = await client.models.embedContent({
        model: 'text-embedding-004',
        contents: text
      });
      return response.embeddings?.[0]?.values || [];
    } catch (error: any) {
      throw new Error(`Embedding computation failed: ${error.message}`);
    }
  }

  /**
   * Searches the Knowledge Base via Postgres pgvector COSINE distance operators.
   */
  async search(query: string, limit: number = 3): Promise<{ documentId: string; content: string; similarity: number }[]> {
    try {
      const embedding = await this.embed(query);
      if (!embedding.length) return [];

      const vectorStr = `[${embedding.join(',')}]`;

      const results = await prisma.$queryRawUnsafe<any[]>(`
        SELECT
          "documentId",
          "content",
          1 - (embedding <=> $1::vector) as similarity
        FROM "DocumentEmbedding"
        ORDER BY embedding <=> $1::vector
        LIMIT $2;
      `, vectorStr, limit);

      return results;
    } catch (error: any) {
      throw new Error(`Vector Semantic Search failed: ${error.message}`);
    }
  }
}
